In [ ]:
import numpy as np


In [ ]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
a=[1,2,3,"helllo",3.5]
a

[1, 2, 3, 'helllo', 3.5]

In [ ]:
np.array(a)

array(['1', '2', '3', 'helllo', '3.5'], dtype='<U32')

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.zeros((6,6))
arr


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr=np.arange(1,18)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
arr=np.arange(1,18,2)
arr


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
import numpy as np
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr=np.ones((2,2))
arr


array([[1., 1.],
       [1., 1.]])

In [ ]:
arr=np.linspace(1,5)
arr


array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
arr=np.linspace(0,2,11)
arr


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [ ]:
np.random.rand(10)

array([0.88742749, 0.37273484, 0.08879715, 0.52068184, 0.2745034 ,
       0.48171479, 0.86728204, 0.99018049, 0.04194864, 0.72842181])

In [ ]:
np.random.rand(10)

array([0.42598642, 0.748219  , 0.19311319, 0.98341601, 0.51920007,
       0.59678508, 0.44001626, 0.39569016, 0.50498784, 0.0741141 ])

In [ ]:
np.random.randint(10,20,10)

array([15, 10, 16, 14, 17, 19, 17, 14, 10, 18])

In [ ]:
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()


np.int64(45)

In [ ]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#numpy indexing and slicing og vecotrs

arr=np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[6]

np.int64(17)

In [ ]:
arr[9]

np.int64(20)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
arr[4]

np.int64(15)

In [ ]:
#nupy indexing and slicing of matrix

arr=np.arange(1,31).reshape(6,5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5,3]

np.int64(29)

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
#boolean indexing
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#boolena indexing

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr %2
bool_index

array([0, 1, 0, 1, 0])

In [ ]:
bool_index=arr>15
bool_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr=arr[bool_index]
arr

array([16, 17, 18, 19, 20])

In [ ]:
#array operations
#arithmetic operaions
#broadcastin
#deepa dn shallow copy
# matrix oerations
#advance array manipulation
#staking array
#splittin array


In [ ]:
import numpy as np

In [ ]:
#arithmetic operations

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [ ]:

a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
#a1 - a2
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
#they shoud have the same size


In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 /a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
#broadcasting

In [ ]:
l=[10,20,30,40]
arr=np.array(l)


In [ ]:
l +10
#it is not possible

TypeError: can only concatenate list (not "int") to list

In [ ]:
arr+10

array([20, 30, 40, 50])

In [ ]:
arr *20


array([200, 400, 600, 800])

In [ ]:
arr2=np.arange(1,26).reshape(5,5)

In [ ]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
arr2 *2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [ ]:
#deep and shallow copy
#.      ----ther will de not change in the main array if we slice


In [ ]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[0:5]
slice *10

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b=a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#matrix operations

In [ ]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
a *a

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [ ]:
a@a
#this is multiplication of matrix


array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

In [ ]:
np.dot(a,a)

array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

In [ ]:
#transpose of matrix


In [ ]:
np.transpose(a)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [ ]:
a.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [ ]:
a.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [ ]:
#advane array manipulations


In [ ]:
#stacking array
 # ----- we cannt do for matrix note this


In [ ]:
a=np.arange(1,5)
a
b=np.arange(5,9)
a
b

array([5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [ ]:
np.hstack((a,a))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
np.row_stack((a,b))

/tmp/ipython-input-1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
for i in c:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [ ]:
#valid sudoko


In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

np.int64(916)

In [ ]:
data.shape

(5, 3)

In [ ]:
np.mean(data)

np.float64(61.06666666666667)

In [ ]:
#find the average age of student
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
#extract math marks of all students
data[:,1]


array([85, 92, 76, 65, 90])

In [ ]:
#find the hghest scinec marks
slice=data[:,2]
np.max(slice)


np.int64(95)

In [ ]:
#get the details of student who scored more than 90 in math

In [ ]:
data[:,1] >90

array([False,  True, False, False, False])

In [ ]:
slice=data[:,1]
slice =slice+5
slice

array([90, 97, 81, 70, 95])

In [ ]:
#find who many students are younder than 19

In [ ]:
data[data[:,0]>19].size

3

In [ ]:
#calculate the average marks in eachs subjaect

In [ ]:
data[:,1:]

array([[85, 78],
       [92, 88],
       [76, 95],
       [65, 70],
       [90, 85]])

In [ ]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [ ]:
#get data of student who scored at least 80 in both subjects

In [ ]:
data[(data[:,1]>80) & (data[:,2]>80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#replace all scienc emarks <75 with 0

In [ ]:
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])